### ISSUE TITLE
postcss overwrite use mode:'file' will  cause crash

### ISSUE THREAD

**Issue by scliuyang** [gsoft-inc/craco#357] opened 2021-12-21 07:40 UTC
craco: 6.4.3
react-scripts: 5.0.0

craco.config.js
```javascript
style: {
    postcss: {
      mode: 'file',
      loaderOptions: {
        config: {
          path: path.resolve(__dirname, './postcss.config.js'),
        },
      },
    },
  }
```
error:
![image](https://user-images.githubusercontent.com/12167648/146889938-32af0de3-9f65-466a-ae39-47a34942b6bb.png)

why:
https://github.com/gsoft-inc/craco/blob/master/packages/craco/lib/features/webpack/style/postcss.js#L29

craco read  **match.loader.options.ident**
but react-scripts move ident to **postcssOptions**
https://github.com/facebook/create-react-app/blob/v5.0.0/packages/react-scripts/config/webpack.config.js#L139

it create less plugin crash

**Comment by patricklafrance** [comment] 2022-01-13 18:15
Duplicate of https://github.com/gsoft-inc/craco/issues/378

**Closed by patricklafrance** 2022-01-13 18:15 UTC
