### ISSUE TITLE
Update CRACO for create-react-app v5

### ISSUE THREAD

**Issue by tom-ricci** [gsoft-inc/craco#353] opened 2021-12-14 17:11 UTC
Create-react-app v5 was just released an hour ago https://github.com/facebook/create-react-app/releases/tag/v5.0.0 and CRACO should probably update to v5 soon.

**Comment by OriAmir** [comment] 2021-12-14 21:10
Yeah! I worked with react script 5 next version for a while and craco and things looks OK for me .. 
wait for the official support of CRACo in CRA5, thanks for your work !

**Comment by ajgassner** [comment] 2021-12-14 22:05
I just tried it out and it seems the craco-less plugin isn't compatible for now. We will stay at V4 until this issue has been fixed. We need craco-less to compile the less stylesheets of antd.

**Comment by supriome** [comment] 2021-12-14 23:25
#313 https://github.com/gsoft-inc/craco/issues/313#issuecomment-970810867

I also have this problem and hope that it will be fixed soon, and a new version of carco will be released that supports CRA5

**Comment by xyy94813** [comment] 2021-12-15 03:21
I found some dependencies some of react-scrips's dependencies are in node_modules under directory react-scripts.

An implementation like this:
https://github.com/gsoft-inc/craco/blob/8ab5cc92a963f1ed1c3c223ea46aea0cea5d6632/packages/craco/lib/features/webpack/style/postcss.js#L16

it will cause cannot find module problem

**Comment by xyy94813** [comment] 2021-12-15 03:25
About `craco-less` see https://github.com/DocSpring/craco-less/issues/86#issuecomment-994256486

**Comment by supriome** [comment] 2021-12-15 04:16
The problem is this line.

https://github.com/gsoft-inc/craco/blob/8ab5cc92a963f1ed1c3c223ea46aea0cea5d6632/packages/craco/lib/features/webpack/style/postcss.js#L54

webpack 5 use  [postcssOptions](https://github.com/webpack-contrib/postcss-loader#postcssoptions) as postcss-loader option,while webpack 4 use loader in this way.
```
webpack 5 use this way
{
  loader: "postcss-loader",
  options: {
    postcssOptions: {
      plugins: [],
    },
  },
},

webpack 4 use this way
{
  loader: "postcss-loader",
  options: {
    plugins: [],
  },
},
```
 In webpack 4, `match.loader.options.plugins();` return a function. And In webpack 5 `match.loader.options.postcssOptions.plugins;` return a object of a function. [Click this link to see postcssOptions  Description](https://github.com/webpack-contrib/postcss-loader#options)
![image](https://user-images.githubusercontent.com/19944032/146122120-0a58c7bb-3d16-477c-be04-18a2a934f13f.png)

So maybe there another way to get postcssPlugins. Hope this will be fixed soon.

**Comment by denchen** [comment] 2021-12-15 05:37
Anyone else have issues with Jest? I'm getting:

```
  ● Test suite failed to run

    TypeError: babelJest.createTransformer is not a function

      at createJestBabelTransform (node_modules/@craco/craco/lib/features/jest/create-jest-babel-transform.js:56:22)
      at Object.<anonymous> (node_modules/@craco/craco/lib/features/jest/jest-babel-transform.js:9:8)
      at require.extensions.<computed> (node_modules/ts-node/src/index.ts:1361:43)
      at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:1361:43)
```

```
& npm ls babel-jest
my-ui@2.2.5 /Users/denchen/git/ui
└─┬ react-scripts@5.0.0 invalid: "^4.0.0" from node_modules/@craco/craco
  ├── babel-jest@27.4.5
  └─┬ jest@27.4.5
    └─┬ @jest/core@27.4.5
      └─┬ jest-config@27.4.5
        └── babel-jest@27.4.5 deduped
```

**Comment by docmars** [comment] 2021-12-15 18:59
Using craco `6.4.3` next to CRA 5 with only 1 plugin: `craco-alias`, and things appear to be working swimmingly. Will report back here if anything comes up.

**Comment by docmars** [comment] 2021-12-15 19:34
Adding for reference material: @jaxyeh forked and did some nice work on this about a month ago. May be useful if any workarounds are necessary:
https://github.com/jaxyeh/craco/commit/9f3faa7fd969546407bd485ce6db07078390d7f1

**Comment by Nefcanto** [comment] 2021-12-18 12:30
I'm using Tailwind 3 and here's my `craco.config.js`:

```
module.exports = {
  style: {
    postcss: {
      plugins: [
        require('tailwindcss'),
        require('autoprefixer'),
      ],
    },
  },
  webpack: {
    alias: resolvedAliases,
    // this config, causes HolismIcon to throw react error 321 for builds
    configure: {
      resolve: {
        symlinks: false,
      },
    },
  },
}
```

I upgraded my `react-scripts` from V4 to V5 and it gives me this error:

> TypeError: match.loader.options.plugins is not a function

**Comment by Nefcanto** [comment] 2021-12-18 13:09
Here's what I get now when I try to install `craco` on `create-react-app`:

```
npm install @craco/craco --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: sample@0.1.0
npm ERR! Found: react-scripts@5.0.0
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"5.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-scripts@"^4.0.0" from @craco/craco@6.4.3
npm ERR! node_modules/@craco/craco
npm ERR!   @craco/craco@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-18T13_07_05_364Z-debug-0.log
```

**Comment by OriAmir** [comment] 2021-12-18 18:24
> Here's what I get now when I try to install `craco` on `create-react-app`:
> 
> ```
> npm install @craco/craco --save
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: sample@0.1.0
> npm ERR! Found: react-scripts@5.0.0
> npm ERR! node_modules/react-scripts
> npm ERR!   react-scripts@"5.0.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react-scripts@"^4.0.0" from @craco/craco@6.4.3
> npm ERR! node_modules/@craco/craco
> npm ERR!   @craco/craco@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /root/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-12-18T13_07_05_364Z-debug-0.log
> ```

it's because craco peer dep is` react-scripts `version 4 , when they will update that it's will be fine.
You can resolve when now with that flag : `--legacy-peer-deps` -> `npm install craco --legacy-peer-deps` , it's happening in NPM>6 thst it's try to install also the peer deps , read more here: https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh

**Comment by kiril-daskalov** [comment] 2021-12-19 07:49
> I'm using Tailwind 3 and here's my `craco.config.js`:
> 
> ```
> module.exports = {
>   style: {
>     postcss: {
>       plugins: [
>         require('tailwindcss'),
>         require('autoprefixer'),
>       ],
>     },
>   },
>   webpack: {
>     alias: resolvedAliases,
>     // this config, causes HolismIcon to throw react error 321 for builds
>     configure: {
>       resolve: {
>         symlinks: false,
>       },
>     },
>   },
> }
> ```
> 
> I upgraded my `react-scripts` from V4 to V5 and it gives me this error:
> 
> > TypeError: match.loader.options.plugins is not a function


Tailwind 3 configuration in CRACO is not needed anymore.

https://tailwindcss.com/docs/guides/create-react-app

**Comment by Nefcanto** [comment] 2021-12-20 11:37
@kiril-daskalov yeah Tailwind 3 does not need CRACO anymore. But I still need CRACO because of Webpack aliases and symbolic links.

**Comment by Nefcanto** [comment] 2021-12-20 12:11
I upgraded to Tailwind 3. Now my app works in the development environment. However, my app breaks in build.

Here's my `craco.config.js` file:

```
const path = require(`path`);
const aliases = {
    '@Form': 'src/Components/Form/Form',
    '@FormTwo': 'src/Components/Form/FormTwo',
    '@List': 'src/Components/List/List',
    '@Browse': 'src/Components/Browse/Browse',
    '@Dashboard': 'src/Components/Dashboard/Dashboard',
    '@Panel': 'src/Panel/Panel',
};

const resolvedAliases = Object.fromEntries(
    Object.entries(aliases).map(([key, value]) => [key, path.resolve(__dirname, value)]),
);

module.exports = {
    webpack: {
        alias: resolvedAliases
    }
}
```

It fails with this message:

```
Step 13/20 : RUN npm run build
 ---> Running in 7629d400606c

> panel@0.1.0 build
> craco build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '...' in '/Company/Project/src'


The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

**Comment by jamshally** [comment] 2021-12-20 14:29
> Anyone else have issues with Jest? I'm getting:
> 
> ```
>   ● Test suite failed to run
> 
>     TypeError: babelJest.createTransformer is not a function
> 
>       at createJestBabelTransform (node_modules/@craco/craco/lib/features/jest/create-jest-babel-transform.js:56:22)
>       at Object.<anonymous> (node_modules/@craco/craco/lib/features/jest/jest-babel-transform.js:9:8)
>       at require.extensions.<computed> (node_modules/ts-node/src/index.ts:1361:43)
>       at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:1361:43)
> ```
> 
> ```
> % npm ls babel-jest
> my-ui@2.2.5 /Users/denchen/git/ui
> └─┬ react-scripts@5.0.0 invalid: "^4.0.0" from node_modules/@craco/craco
>   ├── babel-jest@27.4.5
>   └─┬ jest@27.4.5
>     └─┬ @jest/core@27.4.5
>       └─┬ jest-config@27.4.5
>         └── babel-jest@27.4.5 deduped
> ```

I am getting the exact issue as @denchen. I haven't found a solution yet. Adding here for visibility.

**Comment by cgooderham94** [comment] 2021-12-22 21:58
> > Anyone else have issues with Jest? I'm getting:
> > ```
> >   ● Test suite failed to run
> > 
> >     TypeError: babelJest.createTransformer is not a function
> > 
> >       at createJestBabelTransform (node_modules/@craco/craco/lib/features/jest/create-jest-babel-transform.js:56:22)
> >       at Object.<anonymous> (node_modules/@craco/craco/lib/features/jest/jest-babel-transform.js:9:8)
> >       at require.extensions.<computed> (node_modules/ts-node/src/index.ts:1361:43)
> >       at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:1361:43)
> > ```    
> >   
> > ```
> > % npm ls babel-jest
> > my-ui@2.2.5 /Users/denchen/git/ui
> > └─┬ react-scripts@5.0.0 invalid: "^4.0.0" from node_modules/@craco/craco
> >   ├── babel-jest@27.4.5
> >   └─┬ jest@27.4.5
> >     └─┬ @jest/core@27.4.5
> >       └─┬ jest-config@27.4.5
> >         └── babel-jest@27.4.5 deduped
> > ```
> 
> I am getting the exact issue as @denchen. I haven't found a solution yet. Adding here for visibility.

Ditto - I too face the same issue as @denchen and @jamshally - It seems this is becoming a common issue. Is it possible there is a workaround or if a fix may be implemented soon?

```
charliegooderham.dev@0.1.0 /Users/charlesgooderham/htdocs/charliegooderham.dev
├─┬ jest@27.4.5
│ └─┬ @jest/core@27.4.5
│   └─┬ jest-config@27.4.5
│     └── babel-jest@27.4.5 deduped
├─┬ react-scripts@5.0.0
│ └── babel-jest@27.4.5
└─┬ ts-jest@27.1.2
  └── babel-jest@27.4.5
```

**Comment by mpsijm** [comment] 2021-12-23 15:10
I updated `react-scripts` to 5.0.0 today (with `npm i --legacy-peer-deps`), and it runs mostly fine for me. I use Tailwind v3 as well. I only have the following minor issues:

- Webpack v5 no longer polyfills Node's core modules, so as a workaround, I added the `node-polyfill-webpack-plugin` to my `craco.config.js`: https://stackoverflow.com/a/65556946. I'm not sure if this is caused by one of my dependencies or by CRACO.
- I get deprecation warnings when running `craco start`, right before it clears the console:
    ![image](https://user-images.githubusercontent.com/9739541/147256374-5c0e4c09-65cd-4099-b10d-c4d1813d026e.png)

**Comment by ihoey** [comment] 2021-12-24 03:52
> I just tried it out and it seems the craco-less plugin isn't compatible for now. We will stay at V4 until this issue has been fixed. We need craco-less to compile the less stylesheets of antd.

 craco-less already fixed

**Comment by popuguytheparrot** [comment] 2021-12-24 13:37
TypeError: babelJest.createTransformer is not a function
    at createJestBabelTransform (/Users/ruattr2/WebstormProjects/corpcrm-ui/node_modules/@craco/craco/lib/features/jest/create-jest-babel-transform.js:56:22)

**Comment by AmirAsghary** [comment] 2021-12-24 13:52
Is there an ETA for the CRACO's support for webpackV5?

**Comment by Nefcanto** [comment] 2021-12-26 18:37
Any news regarding this upgrade? We are faced with the `eject` decision and we don't really want to do it. CRACO is a neat solution.

**Comment by patricklafrance** [comment] 2021-12-26 21:37
Info available here https://github.com/gsoft-inc/craco/issues/313

**Comment by cabello** [comment] 2021-12-27 19:07
In my case as soon as I upgraded react-scripts:
```
Module not found: Error: You attempted to import /Users/cabello/project/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
```
I also got different errors depending on what I attempted to update.

And this is my craco config:

```javascript
const CopyWebpackPlugin = require('copy-webpack-plugin');
const RollbarSourceMapPlugin = require('rollbar-sourcemap-webpack-plugin');

const rollbarPlugin = {
  overrideWebpackConfig: ({ webpackConfig }) => {
    if (process.env.GENERATE_SOURCEMAP === 'true') {
      webpackConfig.plugins.push(
        new RollbarSourceMapPlugin({
          accessToken: process.env.ROLLBAR_ACCESS_TOKEN,
          publicPath: 'https://example.com',
          version: process.env.REACT_APP_COMMIT_REF,
        })
      );
    }
    return webpackConfig;
  },
};

module.exports = {
  plugins: [{ plugin: rollbarPlugin }],
  babel: {
    loaderOptions: (babelLoaderOptions) => {
      const origBabelPresetCRAIndex = babelLoaderOptions.presets.findIndex(
        (preset) => {
          return preset[0].includes('babel-preset-react-app');
        }
      );

      const origBabelPresetCRA =
        babelLoaderOptions.presets[origBabelPresetCRAIndex];

      babelLoaderOptions.presets[
        origBabelPresetCRAIndex
      ] = function overridenPresetCRA(api, opts, env) {
        const babelPresetCRAResult = require(origBabelPresetCRA[0])(
          api,
          origBabelPresetCRA[1],
          env
        );

        babelPresetCRAResult.presets.forEach((preset) => {
          // detect @babel/preset-react with {development: true, runtime: 'automatic'}
          const isReactPreset =
            preset &&
            preset[1] &&
            preset[1].runtime === 'automatic' &&
            preset[1].development === true;
          if (isReactPreset) {
            preset[1].importSource = '@welldone-software/why-did-you-render';
          }
        });

        return babelPresetCRAResult;
      };

      return babelLoaderOptions;
    },
    plugins: [
      [
        'react-intl',
        {
          idInterpolationPattern: '[sha512:contenthash:base64:6]',
          extractFromFormatMessageCall: true,
          ast: true,
        },
      ],
    ],
  },
  webpack: {
    plugins: {
      alias: {
        'react-redux':
          process.env.NODE_ENV === 'development'
            ? 'react-redux/lib'
            : 'react-redux',
      },
      add: [
        new CopyWebpackPlugin({
          patterns: [
            {
              from: 'node_modules/some-library',
              to: 'some-library',
            },
          ],
        }),
      ],
    },
  },
};
```

**Comment by edvincandon** [comment] 2021-12-31 07:59
> > Anyone else have issues with Jest? I'm getting:
> > ```
> >   ● Test suite failed to run
> > 
> >     TypeError: babelJest.createTransformer is not a function
> > 
> >       at createJestBabelTransform (node_modules/@craco/craco/lib/features/jest/create-jest-babel-transform.js:56:22)
> >       at Object.<anonymous> (node_modules/@craco/craco/lib/features/jest/jest-babel-transform.js:9:8)
> >       at require.extensions.<computed> (node_modules/ts-node/src/index.ts:1361:43)
> >       at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:1361:43)
> > ```
> > ```
> > % npm ls babel-jest
> > my-ui@2.2.5 /Users/denchen/git/ui
> > └─┬ react-scripts@5.0.0 invalid: "^4.0.0" from node_modules/@craco/craco
> >   ├── babel-jest@27.4.5
> >   └─┬ jest@27.4.5
> >     └─┬ @jest/core@27.4.5
> >       └─┬ jest-config@27.4.5
> >         └── babel-jest@27.4.5 deduped
> > ```
> 
> I am getting the exact issue as @denchen. I haven't found a solution yet. Adding here for visibility.

Same problem here, got it to work by fiddling around in my `node_modules`. I'd open a PR, but I'm not well-versed enough on the craco codebase yet to have a proper solution covering all cases. 

#### Environment 

```
node v15.14.0
craco v6.4.3
react-scripts v5.0.0
jest v27.4.5
```

craco.config.js (jest)
```javascript
module.exports = {
  /* ... */
  jest: {
        configure: (jestConfig, { env, paths, resolve, rootDir }) => {
            jestConfig.setupFilesAfterEnv.push(`${rootDir}/../../jest.setup.js`);

            /* avoid ES modules */
            jestConfig.moduleNameMapper['^lodash-es$'] = 'lodash';
            jestConfig.moduleNameMapper['^@antv/xflow-core/es/(.*)'] = '@antv/xflow-core/lib/$1';

            return jestConfig;
        }
    }
}
```

#### Resolution steps 

https://github.com/gsoft-inc/craco/blob/8ab5cc92a963f1ed1c3c223ea46aea0cea5d6632/packages/craco/lib/features/jest/create-jest-babel-transform.js#L56 

You actually just need to call it from the default export (https://github.com/facebook/jest/issues/11444)
```javascript
return babelJest.default.createTransformer(craBabelTransformer);
```
---
https://github.com/gsoft-inc/craco/blob/8ab5cc92a963f1ed1c3c223ea46aea0cea5d6632/packages/craco/lib/features/jest/jest-babel-transform.js#L12

For some reason (haven't really checked the full codebase : don't know what dependency update caused this) - the correct path to access the jest globals object would be 
```javascript
jestBabelTransform = createJestBabelTransform(config.config.globals._cracoConfig);
```
---

Hope it can help while we wait for a fix (or this to turn into a PR ?)..

**Comment by flyingCrp** [comment] 2022-01-01 14:21
> I just tried it out and it seems the craco-less plugin isn't compatible for now. We will stay at V4 until this issue has been fixed. We need craco-less to compile the less stylesheets of antd.

time to move on,😄   [feat: support for CRA v5](https://github.com/DocSpring/craco-less/pull/88)

**Comment by FezVrasta** [comment] 2022-01-04 18:43
I get this with an empty craco config, ideas?

```
Failed to compile.

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[1].oneOf[9].type should be one of these:
   "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
   -> Module type to use for the module
 - configuration.output has an unknown property 'assetModuleFilename'. These properties are valid:
   object { auxiliaryComment?, chunkCallbackName?, chunkFilename?, chunkLoadTimeout?, crossOriginLoading?, devtoolFallbackModuleFilenameTemplate?, devtoolLineToLine?, devtoolModuleFilenameTemplate?, devtoolNamespace?, filename?, futureEmitAssets?, globalObject?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, jsonpFunction?, jsonpScriptType?, library?, libraryExport?, libraryTarget?, path?, pathinfo?, publicPath?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine?, webassemblyModuleFilename? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
 - configuration.target should be one of these:
   "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron-preload" | function
   -> Environment to build for
   Details:
    * configuration.target should be one of these:
      "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron-preload"
    * configuration.target should be an instance of function

```

**Comment by andycanderson** [comment] 2022-01-04 18:48
> > I just tried it out and it seems the craco-less plugin isn't compatible for now. We will stay at V4 until this issue has been fixed. We need craco-less to compile the less stylesheets of antd.
> 
> time to move on,😄 [feat: support for CRA v5](https://github.com/DocSpring/craco-less/pull/88)

What version craco-less are you using? At a glance "craco-less": "^2.0.0", seems to be working

**Comment by thehogfather** [comment] 2022-01-11 21:40
> > > Anyone else have issues with Jest? I'm getting:
> > > ```
> > >   ● Test suite failed to run
> > > 
> > >     TypeError: babelJest.createTransformer is not a function
> > > 
> > >       at createJestBabelTransform (node_modules/@craco/craco/lib/features/jest/create-jest-babel-transform.js:56:22)
> > >       at Object.<anonymous> (node_modules/@craco/craco/lib/features/jest/jest-babel-transform.js:9:8)
> > >       at require.extensions.<computed> (node_modules/ts-node/src/index.ts:1361:43)
> > >       at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:1361:43)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > % npm ls babel-jest
> > > my-ui@2.2.5 /Users/denchen/git/ui
> > > └─┬ react-scripts@5.0.0 invalid: "^4.0.0" from node_modules/@craco/craco
> > >   ├── babel-jest@27.4.5
> > >   └─┬ jest@27.4.5
> > >     └─┬ @jest/core@27.4.5
> > >       └─┬ jest-config@27.4.5
> > >         └── babel-jest@27.4.5 deduped
> > > ```
> > 
> > 
> > I am getting the exact issue as @denchen. I haven't found a solution yet. Adding here for visibility.
> 
> Ditto - I too face the same issue as @denchen and @jamshally - It seems this is becoming a common issue. Is it possible there is a workaround or if a fix may be implemented soon?
> 
> ```
> charliegooderham.dev@0.1.0 /Users/charlesgooderham/htdocs/charliegooderham.dev
> ├─┬ jest@27.4.5
> │ └─┬ @jest/core@27.4.5
> │   └─┬ jest-config@27.4.5
> │     └── babel-jest@27.4.5 deduped
> ├─┬ react-scripts@5.0.0
> │ └── babel-jest@27.4.5
> └─┬ ts-jest@27.1.2
>   └── babel-jest@27.4.5
> ```

One possible work around for the babel-jest issue (until a new version of craco that supports react-scripts 5 is released) is to update your package.json to use the underlying `react-scripts` instead of `craco` for tests. You would also need to move any jest specific configs from craco to the package.json file. Might not work if you have very complex webpack setup for tests. So for example:
Before in package.json `"scripts"` section:
```js
    "test": "craco test --env=jsdom",
```

After
```js
    "test": "react-scripts test --env=jsdom",
```

**Comment by kitayoshi** [comment] 2022-01-13 07:27
@supriome I used patch-package to patch this file of `@craco/craco@6.4.3` like:

```diff
diff --git a/node_modules/@craco/craco/lib/features/webpack/style/postcss.js b/node_modules/@craco/craco/lib/features/webpack/style/postcss.js
index c66146a..31372ef 100644
--- a/node_modules/@craco/craco/lib/features/webpack/style/postcss.js
+++ b/node_modules/@craco/craco/lib/features/webpack/style/postcss.js
@@ -50,8 +50,12 @@ function extendsPostcss(match, { plugins, env }) {
         } else {
             let craPlugins = [];
 
-            if (match.loader.options) {
-                craPlugins = match.loader.options.plugins();
+            if (match.loader.options.postcssOptions) {
+                if (typeof match.loader.options.postcssOptions === "function") {
+                    craPlugins = match.loader.options.postcssOptions().plugins;
+                } else {
+                    craPlugins = match.loader.options.postcssOptions.plugins;
+                }
             }
 
             postcssPlugins = craPlugins || [];
@@ -63,13 +67,20 @@ function extendsPostcss(match, { plugins, env }) {
             log("Added PostCSS plugins.");
         }
 
-        if (match.loader.options) {
-            match.loader.options.plugins = () => postcssPlugins;
-        } else {
-            match.loader.options = {
-                plugins: () => postcssPlugins
-            };
+        let postcssOptions
+
+        if (match.loader.options.postcssOptions) {
+            if (typeof match.loader.options.postcssOptions === "function") {
+                postcssOptions = match.loader.options.postcssOptions();
+            } else {
+                postcssOptions = match.loader.options.postcssOptions
+            }
         }
+
+        match.loader.options.postcssOptions = () => ({
+            ...postcssOptions,
+            plugins: postcssPlugins
+        });
     }
 }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by agusterodin** [comment] 2022-01-13 15:23
> > 
> 
> craco is still needed with tailwind 3 for anyone using `postcss-import` or other extensions. https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports

Or something as simple as using a tailwind config file from any path other than the project root (tailwind config file housed in a common UI library, for example)

**Comment by patricklafrance** [comment] 2022-01-13 18:12
Duplicate of https://github.com/gsoft-inc/craco/issues/378

**Closed by patricklafrance** 2022-01-13 18:12 UTC

**Comment by tom-ricci** [comment] 2022-01-13 20:41
Isn't 378 technically a duplicate of this? :p

/j

**Comment by patricklafrance** [comment] 2022-01-13 20:48
@tom-ricci hehe yeah technically you're right ;)

**Comment by xyy94813** [comment] 2022-01-17 06:39
> > > > Anyone else have issues with Jest? I'm getting:
> > > > ```
> > > >   ● Test suite failed to run
> > > > 
> > > >     TypeError: babelJest.createTransformer is not a function
> > > > 
> > > >       at createJestBabelTransform (node_modules/@craco/craco/lib/features/jest/create-jest-babel-transform.js:56:22)
> > > >       at Object.<anonymous> (node_modules/@craco/craco/lib/features/jest/jest-babel-transform.js:9:8)
> > > >       at require.extensions.<computed> (node_modules/ts-node/src/index.ts:1361:43)
> > > >       at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:1361:43)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > % npm ls babel-jest
> > > > my-ui@2.2.5 /Users/denchen/git/ui
> > > > └─┬ react-scripts@5.0.0 invalid: "^4.0.0" from node_modules/@craco/craco
> > > >   ├── babel-jest@27.4.5
> > > >   └─┬ jest@27.4.5
> > > >     └─┬ @jest/core@27.4.5
> > > >       └─┬ jest-config@27.4.5
> > > >         └── babel-jest@27.4.5 deduped
> > > > ```
> > > 
> > > 
> > > I am getting the exact issue as @denchen. I haven't found a solution yet. Adding here for visibility.
> > 
> > 
> > Ditto - I too face the same issue as @denchen and @jamshally - It seems this is becoming a common issue. Is it possible there is a workaround or if a fix may be implemented soon?
> > ```
> > charliegooderham.dev@0.1.0 /Users/charlesgooderham/htdocs/charliegooderham.dev
> > ├─┬ jest@27.4.5
> > │ └─┬ @jest/core@27.4.5
> > │   └─┬ jest-config@27.4.5
> > │     └── babel-jest@27.4.5 deduped
> > ├─┬ react-scripts@5.0.0
> > │ └── babel-jest@27.4.5
> > └─┬ ts-jest@27.1.2
> >   └── babel-jest@27.4.5
> > ```
> 
> One possible work around for the babel-jest issue (until a new version of craco that supports react-scripts 5 is released) is to update your package.json to use the underlying `react-scripts` instead of `craco` for tests. You would also need to move any jest specific configs from craco to the package.json file. Might not work if you have very complex webpack setup for tests. So for example: Before in package.json `"scripts"` section:
> 
> ```js
>     "test": "craco test --env=jsdom",
> ```
> 
> After
> 
> ```js
>     "test": "react-scripts test --env=jsdom",
> ```

My workaround in current version of CRACO:

```js
// craco.config.js
jest: {
    configure: jestConfig => lodash.merge(jestConfig, {
      transform: {
        // https://github.com/gsoft-inc/craco/issues/353#issuecomment-1003301013
        '^.+\\.(js|jsx|mjs|cjs|ts|tsx)$': './libs/jest-babel-transform.js',
      },
    }),
  },
```

```js
// jest-babel-transform.js

/* eslint-disable no-underscore-dangle */
/* eslint-disable max-len */
// eslint-disable-next-line import/no-extraneous-dependencies
const babelJest = require('babel-jest');

const { isArray } = Array;

/**
 * To check if support jsx-runtime
 * Copy from https://github.com/facebook/create-react-app/blob/2b1161b34641bb4d2f269661cd636bbcd4888406/packages/react-scripts/config/jest/babelTransform.js#L12
 */
const hasJsxRuntime = (() => {
  if (process.env.DISABLE_NEW_JSX_TRANSFORM === 'true') {
    return false;
  }

  try {
    require.resolve('react/jsx-runtime');
    return true;
  } catch (e) {
    return false;
  }
})();

function createJestBabelTransform(cracoConfig) {
  const craBabelTransformer = {
    presets: [
      [
        'babel-preset-react-app',
        {
          runtime: hasJsxRuntime ? 'automatic' : 'classic',
        },
      ],
    ],
    babelrc: false,
    configFile: false,
  };

  if (cracoConfig) {
    const { addPresets, addPlugins } = cracoConfig.jest.babel;

    if (cracoConfig.babel) {
      if (addPresets) {
        const { presets } = cracoConfig.babel;

        if (isArray(presets)) {
          craBabelTransformer.presets = craBabelTransformer.presets.concat(presets);
        }
      }

      if (addPlugins) {
        const { plugins } = cracoConfig.babel;

        if (isArray(plugins)) {
          craBabelTransformer.plugins = plugins;
        }
      }
    }
  }
  return babelJest.default.createTransformer(craBabelTransformer);
}

let jestBabelTransform;

// cracoConfig is only available inside the transform, but the transform needs to include whatever options cracoConfig
// specifies. So, the first time this transform is run, it generates a new transform -- using cracoConfig -- and
// uses that to process files.
module.exports = {
  ...createJestBabelTransform(),
  process(src, filename, config, transformOptions) {
    if (!jestBabelTransform) {
      jestBabelTransform = createJestBabelTransform(config.config.globals._cracoConfig);
    }

    return jestBabelTransform.process(src, filename, config, transformOptions);
  },
};
```

**Comment by tom-ricci** [comment] 2022-01-17 16:55
@xyy94813 move to #378

**Comment by conatus** [comment] 2022-02-16 16:02
> > > Anyone else have issues with Jest? I'm getting:
> > > ```
> > >   ● Test suite failed to run
> > > 
> > >     TypeError: babelJest.createTransformer is not a function
> > > 
> > >       at createJestBabelTransform (node_modules/@craco/craco/lib/features/jest/create-jest-babel-transform.js:56:22)
> > >       at Object.<anonymous> (node_modules/@craco/craco/lib/features/jest/jest-babel-transform.js:9:8)
> > >       at require.extensions.<computed> (node_modules/ts-node/src/index.ts:1361:43)
> > >       at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:1361:43)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > % npm ls babel-jest
> > > my-ui@2.2.5 /Users/denchen/git/ui
> > > └─┬ react-scripts@5.0.0 invalid: "^4.0.0" from node_modules/@craco/craco
> > >   ├── babel-jest@27.4.5
> > >   └─┬ jest@27.4.5
> > >     └─┬ @jest/core@27.4.5
> > >       └─┬ jest-config@27.4.5
> > >         └── babel-jest@27.4.5 deduped
> > > ```
> > 
> > 
> > I am getting the exact issue as @denchen. I haven't found a solution yet. Adding here for visibility.
> 
> @denchen @jamshally @cgooderham94 - Same problem here, got it to work by fiddling around in my `node_modules`, maybe my resolution can help. I'd open a PR, but I'm not well-versed enough on the craco codebase yet to have a proper solution covering all cases.
> #### Environment
> 
> ```
> node v15.14.0
> craco v6.4.3
> react-scripts v5.0.0
> jest v27.4.5
> ```
> 
> craco.config.js (jest)
> 
> ```js
> module.exports = {
>   /* ... */
>   jest: {
>         configure: (jestConfig, { env, paths, resolve, rootDir }) => {
>             jestConfig.setupFilesAfterEnv.push(`${rootDir}/../../jest.setup.js`);
> 
>             /* avoid ES modules */
>             jestConfig.moduleNameMapper['^lodash-es$'] = 'lodash';
>             jestConfig.moduleNameMapper['^@antv/xflow-core/es/(.*)'] = '@antv/xflow-core/lib/$1';
> 
>             return jestConfig;
>         }
>     }
> }
> ```
> 
> #### Resolution steps
> 
> https://github.com/gsoft-inc/craco/blob/8ab5cc92a963f1ed1c3c223ea46aea0cea5d6632/packages/craco/lib/features/jest/create-jest-babel-transform.js#L56
> 
> You actually just need to call it from the default export ([facebook/jest#11444](https://github.com/facebook/jest/issues/11444))
> 
> ```js
> return babelJest.default.createTransformer(craBabelTransformer);
> ```
> 
> https://github.com/gsoft-inc/craco/blob/8ab5cc92a963f1ed1c3c223ea46aea0cea5d6632/packages/craco/lib/features/jest/jest-babel-transform.js#L12
> 
> For some reason (haven't really checked the full codebase : don't know what dependency update caused this) - the correct path to access the jest globals object would be
> 
> ```js
> jestBabelTransform = createJestBabelTransform(config.config.globals._cracoConfig);
> ```
> 
> Hope it can help while we wait for a fix (or this to turn into a PR ?)..

Thanks for making CRACO!

Having the same issue here.

The [workaround provided](https://github.com/gsoft-inc/craco/issues/353#issuecomment-1014187515) by @xyy94813 works well.

Meanwhile, Jest have released an alpha which makes this problem go away seemingly - https://github.com/facebook/jest/releases/tag/v28.0.0-alpha.1 

It seems that Jest being upgraded to this version in the underlying packages will make this go away. Seems that discussion has moved onto #378, but recording here as this issue doesn't come up over there.
