### ISSUE TITLE
New versions don't work

### ISSUE THREAD

**Issue by pergunt** [gsoft-inc/craco#399] opened 2022-03-01 20:25 UTC
Tried to play with it. Created one project is using v6.4.0 and another one 6.4.3. I noticed that versions > 6.4.0 don't work and after I am trying to run it 

("start" : "craco start" pckg.json) I am facing an error 'craco not found". 
react-scripts: "5.0.0

FYI

**Comment by robbiemu** [comment] 2022-03-17 19:41
possible duplicate of https://github.com/gsoft-inc/craco/issues/378

@pergunt you probably had a failed installation -- if you are using a modern version of node, you could get around **that first issue** by installing like `npm i @craco/craco --legacy-peer-deps` but, yeah, its not pready for prime time with modern react cra

**Comment by dilanx** [comment] 2022-06-05 08:12
Duplicate of #378

**Closed by dilanx** 2022-06-05 08:12 UTC
