### ISSUE TITLE
Could this be a bug?

### ISSUE THREAD

**Issue by liujiayii** [gsoft-inc/craco#376] opened 2022-01-10 16:38 UTC
when I use craco and react-scripts@5,
![image](https://user-images.githubusercontent.com/38902744/148802605-bdc093af-6858-4730-bbd6-cced18530e97.png)
I guess this may have caused the problem?
![image](https://user-images.githubusercontent.com/38902744/148803003-ad4c9242-0d01-4650-92e4-ca06de808585.png)

**Comment by tom-ricci** [comment] 2022-01-11 23:07
#353

**Comment by patricklafrance** [comment] 2022-01-13 18:14
Duplicate of https://github.com/gsoft-inc/craco/issues/378

**Closed by patricklafrance** 2022-01-13 18:14 UTC
