### ISSUE TITLE
Couldn't find a suitable Node resolution for unqualified path node_modules\react-scripts\config\env.js

### ISSUE THREAD

**Issue by umartopia** [gsoft-inc/craco#78] opened 2019-03-19 19:18 UTC
I am using craco and it works fine with yarn.
However, ever since I tried using pnp (plug n play) mode of yarn, I have started getting the issue:

\Client\.pnp.js:21239
    throw firstError;
    ^

Error: Couldn't find a suitable Node resolution for unqualified path "{MyPath}\node_modules\react-scripts\config\env.js"

The issue is that, I cant really give the static path for react scripts (since that is generated by yarn pnp) and thus it is considering that the node_modules would be present in the same directory and fails to compile.

**Comment by umartopia** [comment] 2019-03-22 12:28
Basically we need a switch which we can use for enabling pnp mode of yarn.
something like craco build --enablePnp
OR
craco build --pnp

**Comment by patricklafrance** [comment] 2019-04-02 20:43
Hi @umartopia 

Technically what does that switch will do when enabled?

Thank you,

Patrick

**Comment by umartopia** [comment] 2019-04-04 14:04
Currently, with default mode everything is available under node_modules folder. And all the packages are available at the same level.
node_modules
-- package1
------ package1 files
-- package2
------ package2 files

However, with pnp enabled, there is no folder created for "node_modules" and everything is read from the node cache, which have a different folder structure than node_modules.
So, craco should be able to work fine even with the cache folder structure. (Currently it is expecting the packages to be in the same level as node_modules)

**Comment by patricklafrance** [comment] 2019-04-04 16:36
Thank you @umartopia I'll see what I can do to support pnp

**Comment by patricklafrance** [comment] 2019-04-08 00:57
I am stuck with `Error: You cannot require a package ("react-scripts\config\webpack.config.js") that is not declared in your dependencies (via "C:\Dev\20_gsoft\craco-sandbox\pnp/")`

I found https://yarnpkg.com/en/docs/pnp/troubleshooting but I am not sure how to solve the problem with that information.

Any idea @arcanis ?

This is an hacky scenario were I need to require files from another module and then overwrite the cache of the module with my customized content.

**Comment by arcanis** [comment] 2019-04-08 01:13
Which Yarn version do you use? I think I recognize a bug that got fixed some time ago (incorrect package name detection on Windows because of backslashes).

**Comment by patricklafrance** [comment] 2019-04-08 01:13
@arcanis 1.15.2

**Comment by arcanis** [comment] 2019-04-08 01:20
I can take a look if you provide a full stacktrace + repro steps

**Comment by patricklafrance** [comment] 2019-04-08 01:38
Thank you @arcanis 

Here's a repo to reproduce the error. All the instructions for the setup and repro steps are in the README.

https://github.com/patricklafrance/craco-pnp

**Comment by patricklafrance** [comment] 2019-04-09 14:11
Any lead @arcanis ?

**Comment by umartopia** [comment] 2019-06-03 10:27
@patricklafrance did you get time to check this issue out?

**Comment by patricklafrance** [comment] 2019-06-06 23:14
@umartopia I am stuck with the error mention before. It seems to be impossible with yarn pnp to import a file from a package that is not the main file.

**Comment by umartopia** [comment] 2019-06-10 22:49
@patricklafrance Thanks for looking into this issue. Maybe we can check it back in future (with newer yarn and craco versions)

**Comment by Himadu2000** [comment] 2021-09-27 19:21
Hello I suppose this issue is for pnp support, currently running pnp in a cra app gives following error,
`(node:3224) UnhandledPromiseRejectionWarning: Error: You cannot require a package ("react-scripts\package.json") that is not declared in your dependencies`

Every time I run yarn install I loose SSD drive life and I don't made of money, and the only reason I have to use craco is because of tailwind and that's because those good for nothing Facebook don't update their … dependencies. And I ain't moving to something like nextjs because those … only target is to vendor locking and take money.

And this issue is longer than a year and even though this is closed by a bot so real person can't be responsible.

I know I'm asking a lot in here but it's because I loose more money than my time in issues like this. And I can't make my own fork because things like this takes lot of resources to create and I am going to be the only person to use it. I create 1-3 CRA projects a week and things like this affect a lot.

So somebody please fix this, only thing I can give you is my gratitude and the satisfaction that you are saving SSD life.

**Closed** 2022-06-12 23:13 UTC
Labels: help wanted, wontfix
